config/routes.rb
Budget::Application.routes.draw do

  get "expenses/create"

  root :to => 'spreadsheets#index'

  resources :expenses
  resources :incomes
  resources :accounts
  resources :transfers
  resources :budget_items

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible

  def self.add_account(name)
    account = Account.new
    account.name = name
    account.balance_in_cents = 0
    account.save!
  end

  def self.by_name(account_name)
    if account_name == "Out"
      OutsideAccount.new
    else
      Account.find_by_name!(account_name)
    end
  end

  def self.by_id(account_id)
    Account.find(account_id)
  end

  def self.transferable
    Account.all + [OutsideAccount.new]
  end

  def balance
    Money.new(balance_in_cents)
  end

  def set_balance(new_balance)
    self.balance_in_cents = new_balance.cents
    save!
  end

  def subtract(amount)
    set_balance(balance - amount)
  end

  def add(amount)
    set_balance(balance + amount)
  end

end

class OutsideAccount

  def name
    "Out"
  end

  def add(amount)
  end

  def subtract(amount)
  end

end

app/models/budget_item.rb
class BudgetItem < ActiveRecord::Base
  attr_accessible

  scope :monthly, where(:period => "Monthly")
  scope :yearly, where(:period => "Yearly")

  def self.by_category(category)
    find_by_category!(category)
  end

  def self.add_to_budget(category, period)
    budget_item = BudgetItem.new
    budget_item.category = category
    budget_item.period = period
    budget_item.save!
  end

  def amount
    Money.new(amount_in_cents)
  end

  def set_amount(new_amount)
    self.amount_in_cents = new_amount.cents
    self.save!
  end

  def used_this_month
    Expense.sum_up(Expense.this_month.where(:category => category))
  end

end

app/models/expense.rb
class Expense < ActiveRecord::Base
  attr_accessible

  #default_scope order("date DESC")

  scope :this_month, where(["date >= ?", Date.today.beginning_of_month]).order("date DESC")

  def amount
    Money.new(amount_in_cents)
  end

  def self.by_id(expense_id)
    Expense.find(expense_id)
  end

  def self.report(date, description, category, amount, account)
    create_expense(date, description, category, amount, account)
    Account.by_name(account).subtract(amount)
  end

  def self.sum_up(expense_association)
    expense_association.inject(Money.new(0)) {|sum, x| sum + x.amount}
  end

  def self.default_date
    return Date.today if Expense.count == 0
    Expense.order(:created_at).last.date
  end

  private

    def self.create_expense(date, description, category, amount, account)
      expense = Expense.new
      expense.description = description
      expense.amount_in_cents = amount.cents
      expense.date = date
      expense.category = category
      expense.account = account
      expense.save!
    end

end

app/models/income.rb
class Income < ActiveRecord::Base
  attr_accessible

  default_scope order("date ASC")

  scope :this_month, where(["date >= ?", Date.today.beginning_of_month])

  def amount
    Money.new(amount_in_cents)
  end

  def self.report(date, description, amount)
    create_income(date, description, amount)
    Account.by_name("Checking").add(amount)
  end

  private

    def self.create_income(date, description, amount)
      income = Income.new
      income.date = date
      income.description = description
      income.amount_in_cents = amount.cents
      income.save!
    end

end

app/models/transfer.rb
class Transfer < ActiveRecord::Base
  attr_accessible

  def amount
    Money.new(amount_in_cents)
  end

  def self.execute(date, description, amount, source_account, destination_account)
    create_transfer(date, description, amount, source_account, destination_account)
    Account.by_name(source_account).subtract(amount)
    Account.by_name(destination_account).add(amount)
  end

  private

    def self.create_transfer(date, description, amount, source_account, destination_account)
      transfer = Transfer.new
      transfer.date = date
      transfer.description = description
      transfer.amount_in_cents = amount.cents
      transfer.source_account = source_account
      transfer.destination_account = destination_account
      transfer.save!
    end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
  end

  def new
  end

  def create
    Account.add_account(params[:account][:name])
    redirect_to accounts_url
  end

  def edit
    @account = Account.by_id(params[:id])
  end

  def update
    account = Account.by_id(params[:id])
    account.set_balance(Money.parse(params[:account][:balance]))
    redirect_to accounts_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/budget_items_controller.rb
class BudgetItemsController < ApplicationController
  def index
  end

  def new
  end

  def create
    BudgetItem.add_to_budget(params[:budget_item][:category], params[:budget_item][:period])
    redirect_to budget_items_url
  end

  def edit
    @budget_item = BudgetItem.find(params[:id])
  end

  def update
    budget_item = BudgetItem.find(params[:id])
    budget_item.set_amount(Money.parse(params[:budget_item][:amount]))
    redirect_to budget_items_url
  end

end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController

  def new
  end

  def create
    Expense.report(date, description, category, amount, account_name)
    redirect_to new_expense_url
  end

  def destroy
    expense = Expense.by_id(params[:id])
    Account.by_name(expense.account).add(expense.amount)
    expense.destroy
    redirect_to(:back)
  end

  private

    def date
      Date.parse(params[:expense][:date_string])
    end

    def description
      params[:expense][:description]
    end

    def category
      params[:expense][:category]
    end

    def amount
      Money.parse(params[:expense][:amount])
    end

    def account_name
      params[:expense][:account]
    end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  def new
  end

  def create
    Income.report(date, description, amount)
    redirect_to new_income_url
  end

  private

    def date
      Date.parse(params[:income][:date_string])
    end

    def description
      params[:income][:description]
    end

    def amount
      Money.parse(params[:income][:amount])
    end
end

app/controllers/spreadsheets_controller.rb
class SpreadsheetsController < ApplicationController
  def index
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  def create
    Transfer.execute(Date.parse(params[:transfer][:date_string]), params[:transfer][:description], Money.parse(params[:transfer][:amount]),
                     params[:transfer][:source_account], params[:transfer][:destination_account])
    redirect_to accounts_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_month
    Date.today.strftime("%B")
  end

  def short_date(date)
    date.strftime("%m/%-d")
  end

  def to_html_id(string)
    string.gsub(" ", "-").downcase
  end
end

app/helpers/incomes_helper.rb
module IncomesHelper
end

app/views/accounts/_account_list.html.erb
<br>
<br>
<% Account.all.each do |account| %>
  <div id="<%=to_html_id(account.name) %>">
    <%= account.name %> <%= account.balance.format %> <%= link_to "Edit", edit_account_path(account) %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<%= form_for(@account) do |f| %>
  <%= f.label :balance %>
  <%= f.text_field :balance %>
  <%= f.submit "Save" %>
<% end %>

app/views/accounts/index.html.erb
<%= render "account_list" %>
<br>
<%= link_to "New Account", new_account_path %>

<h2>Transfers</h2>
<table id="transfers">
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
    <th>From</th>
    <th>To</th>
  </tr>
  <% Transfer.all.each do |transfer| %>
    <tr>
      <td><%= short_date(transfer.date) %> </td>
      <td><%= transfer.description %></td>
      <td><%= transfer.amount.format %></td>
      <td><%= transfer.source_account %></td>
      <td><%= transfer.destination_account %></td>
    </tr>
  <% end %>
</table>
<br>
<%= form_for(Transfer.new) do |f| %>
  <%= label_tag 'transfer[date_string]', "Date" %>
  <%= text_field_tag 'transfer[date_string]', short_date(Date.today), :autofocus => true %>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :source_account, "From" %>
  <%= f.select :source_account, options_for_select(Account.transferable.map {|n| [n.name, n.name] }, "Checking") %>
  <%= f.label :destination_account, "To" %>
  <%= f.select :destination_account, options_for_select(Account.transferable.map {|n| [n.name, n.name] }, "Credit Card") %>
  <%= f.submit "Transfer" %>
<% end %>

app/views/accounts/new.html.erb
<%= render "account_list" %>
<br>
<%= form_for(Account.new) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit "Save" %>
<% end %>

app/views/budget_items/_budget.html.erb
<h1>Budget</h1>

<h2>Monthly</h2>
<%= render "items_list", :table_id => "monthly", :items_collection => BudgetItem.monthly %>

<h2>Yearly</h2>
<%= render "items_list", :table_id => "yearly", :items_collection => BudgetItem.yearly %>

app/views/budget_items/_items_list.html.erb
<table id='<%= table_id %>'>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th></th>
  </tr>
  <% items_collection.each do |budget_item| %>
    <tr id='<%= to_html_id(budget_item.category) %>'>
      <td><%=budget_item.category %></td>
      <% if budget_item == @budget_item %>
          <td>
            <%= form_for(@budget_item) do |f| %>
              <%= f.text_field :amount, :autofocus => true %>
              <%= f.submit "Save" %>
            <% end %>
          </td>
          <td></td>
      <% else %>
          <td><%= budget_item.amount.format %></td>
          <td><%= link_to "Edit", edit_budget_item_path(budget_item) %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/budget_items/edit.html.erb
<%= render "budget" %>

app/views/budget_items/index.html.erb
<%= render "budget" %>
<br>
<%= link_to "New Category", new_budget_item_path %>

app/views/budget_items/new.html.erb
<%= render "budget" %>
<br>
<%= form_for(BudgetItem.new) do |f| %>
  <%= f.label :category %>
  <%= f.text_field :category, :autofocus => true %>
  <%= f.select :period, options_for_select([["Monthly", "Monthly"], ["Yearly", "Yearly"]]) %>
  <%= f.submit "Save" %>
<% end %>

app/views/expenses/new.html.erb
<%= render 'layouts/header' %>
<br>
<h2>Expenses</h2>
<table id='expenses'>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
    <th>Category</th>
    <th>Account</th>
    <th></th>
  </tr>
  <%= form_for(Expense.new) do |f| %>
    <tr>
      <td>
        <%= label_tag 'expense[date_string]', "Date", :hidden => true %>
        <%= text_field_tag 'expense[date_string]', short_date(Expense.default_date), :autofocus => true, :size => 5 %>
      </td>
      <td>
        <%= f.label :description, :hidden => true %>
        <%= f.text_field :description%>
      </td>
      <td>
        <%= f.label :amount, :hidden => true %>
        <%= f.text_field :amount, :size => 15 %>
      </td>
      <td>
        <%= f.select :category, options_for_select(BudgetItem.all.map {|n| [n.category, n.category]}) %>
      </td>
      <td>
        <%= f.select :account, options_for_select(Account.all.map {|n| [n.name, n.name] }) %>
      </td>
      <td>
        <%= f.submit "Save" %>
      </td>
    </tr>
  <% end %>

  <% Expense.this_month.each do |expense| %>
    <tr>
      <td><%= short_date(expense.date) %></td>
      <td><%= expense.description %></td>
      <td><%= expense.amount.format %></td>
      <td><%= expense.category %></td>
      <td><%= expense.account %></td>
      <td><%= link_to "[X]", expense_path(expense), :method => :delete %></td>
    </tr>
  <% end %>
</table>
<br>
<br>
<%= render "layouts/category_stats" %>

app/views/incomes/new.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/income' %>
<br>

<%= form_for(Income.new) do |f| %>
  <%= label_tag 'income[date_string]', "Date" %>
  <%= text_field_tag 'income[date_string]', short_date(Date.today), :autofocus => true %>
  <%= f.label :description %>
  <%= f.text_field :description%>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <%= f.submit "Save" %>
<% end %>

app/views/layouts/_category_stats.html.erb
<h2>Stats</h2>
<table id='category-stats'>
  <tr>
    <th>
    <th>Category</th>
    <th>Spent</th>
    <th>Budget</th>
    <th>Remaining</th>
  </tr>
  <tbody id='monthly'>
    <tr><th>Monthly</th></tr>
    <% BudgetItem.monthly.each do |budget_item| %>
      <tr>
        <td></td>
        <td> <%= budget_item.category %> </td>
        <td> <%= budget_item.used_this_month.format %> </td>
        <td> <%= budget_item.amount.format %> </td>
        <td> <%= (budget_item.amount - budget_item.used_this_month).format %> </td>
      </tr>
    <% end %>
  </tbody>
  <tbody id='yearly'>
    <tr><th>Yearly</th></tr>
    <% BudgetItem.yearly.each do |budget_item| %>
      <tr>
        <td></td>
        <td> <%= budget_item.category %> </td>
        <td> <%= budget_item.used_this_month.format %> </td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/layouts/_expenses.html.erb
<h2>Expenses</h2>
<table id='expenses'>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
    <th>Category</th>
    <th>Account</th>
    <th></th>
  </tr>
  <% Expense.this_month.each do |expense| %>
    <tr>
      <td><%= short_date(expense.date) %></td>
      <td><%= expense.description %></td>
      <td><%= expense.amount.format %></td>
      <td><%= expense.category %></td>
      <td><%= expense.account %></td>
      <td><%= link_to "[X]", expense_path(expense), :method => :delete %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/_header.html.erb
<h1><%= current_month %></h1>

<% Account.all.each do |account| %>
<div id='<%= to_html_id(account.name) %>-balance'>
  <%= account.name %> Balance: <%= account.balance.format %>
</div>
<% end %>

app/views/layouts/_income.html.erb
<h2>Income</h2>
<table id='income'>
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th>Amount</th>
  </tr>
  <% Income.this_month.each do |income| %>
    <tr>
      <td><%= short_date(income.date) %></td>
      <td><%= income.description %></td>
      <td><%= income.amount.format %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budget</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Home", root_path %>
<%= link_to "Accounts", accounts_path %>
<%= link_to "Budget", budget_items_path %>

<%= yield %>

</body>
</html>

app/views/line_items/new.html.erb
<%= render "layouts/spreadsheet" %>

<%= form_for(LineItem.new) do |f| %>
  <%= f.select :account, options_for_select(Account.all.map {|n| [n.name, n.name] }) %>
  <%= label_tag 'line_item[date_string]', "Date" %>
  <%= text_field_tag 'line_item[date_string]', short_date(Date.today), :autofocus => true %>
  <%= f.label :description %>
  <%= f.text_field :description%>
  <%= f.label :amount %>
  <%= f.text_field :amount %>
  <%= f.select :category, options_for_select(Category.list.map {|n| [n,n]}) %>
  <%= f.submit "Save" %>
<% end %>
<br>

<%= render "layouts/category_stats" %>

app/views/spreadsheets/index.html.erb
<%= render "layouts/header" %>
<%= render "layouts/income" %>
<%= render "layouts/expenses" %>
<br>
<%= link_to "Add Expenses", new_expense_path %>
<%= link_to "Add Income", new_income_path %>
<br>
<%= render "layouts/category_stats" %>